version = 1

[[migrations]]
id = 7878007080805906285
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 1790021521128812577
name = "0001_stock_params_and_simulations.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 156941947312401389
name = "0002_migration.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 452600738465184114
name = "0003_migration.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 5853304647418316566
name = "0004_remove_stock_profile_id_unique.sql"
snapshot_name = "0004_snapshot.toml"
