version = 1

[schema]

[[schema.tables]]
id = 0
name = "profiles"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "user_id"
ty = "Uuid"
storage_ty = "Uuid"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_profiles_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_profiles_by_user_id"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "stocks"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "name"
ty = "String"
storage_ty = { VarChar = 100 }

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "ticker"
ty = "String"
storage_ty = { VarChar = 5 }

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "profile_id"
ty = "Uuid"
storage_ty = "Uuid"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_stocks_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_stocks_by_profile_id"
on = 1
columns = [{ column = { table = 1, index = 3 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 2
name = "users"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "name"
ty = "String"
storage_ty = { VarChar = 100 }

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "email"
ty = "String"
storage_ty = { VarChar = 320 }

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "password"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_users_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_users_by_email"
on = 2
columns = [{ column = { table = 2, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true
